#!/bin/sh
DEAMON=/usr/bin/aesdsocket
PIDNAME=aesdsocket

case "$1" in
  start)
    echo "Starting AESDSOCKET....."
    start-stop-daemon --start \
        --exec $DEAMON -- -d
    ;;
  stop)
    echo "Stoping AESDSOCKET......"
    start-stop-daemon --stop --name $PIDNAME --retry 5
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
exit 0