#!/bin/sh
module=aesdchar
device=aesdchar
mode="664"

# Group: since distributions do it differently
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

case "$1" in
    start)
        echo "Loading ${module} driver"

        # load from known installed path
        modprobe ${module} || exit 1

        # wait for kernel to register device
        sleep 1

        # get major number from /proc/devices
        major=$(awk "\$2==\"${module}\" {print \$1}" \
                /proc/devices)

        if [ -z "$major" ]; then
            echo "ERROR: could not find major number"
            exit 1
        fi

        echo "${module} major=${major}"

        # create device node
        rm -f /dev/${device}
        mknod /dev/${device} c ${major} 0
        chgrp ${group} /dev/${device}
        chmod ${mode}  /dev/${device}

        echo "Created /dev/${device}"
        ;;

    stop)
        echo "Unloading ${module} driver"
        rm -f /dev/${device}
        rmmod ${module} || true
        echo "Done"
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac